version: "3"
services:
  postgres:
    container_name: learnPrismaPgDocker
    image: postgres:latest
    environment:
      - POSTGRES_USERNAME=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    ports:
      - 5434:5432
    volumes:
      - ./dbdata/:/var/lib/postgresql/data
  pgadmin:
    container_name: learnPrismaPgAdminDocker
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    ports:
      - 5050:80
    depends_on:
      - postgres
    volumes:
      - ./pgadmindata/servers.json:/pgadmin4/servers.json
